### ISSUE TITLE
I can't connect to the Wi-Fi access point "BG Buddy Portal"

### ISSUE THREAD

**Issue by lexhome** [VeryKross/BGBuddy#5]
I compiled BGBuddy_v1.ino myself in Arduino IDE.
I used Wemos D1 mini as the ESP 8266.
When a mobile phone is connected to the Wi-Fi access point "BG Buddy Portal" with the password "12345678", the connection is automatically disconnected.
The following messages are displayed in the Serial Monitor:

Switching to Access Point mode ... Ready
Starting Access Point at 10.10.10.10 ...
Could not connect to WiFi - ask user to connect to Buddy.
Station connected: ee:5c:79:89:e9:72
AID: 1

**Comment by VeryKross** [comment]
That's pretty unusual. Have you tried to connect to its IP address (10.10.10.10) instead of its name?  Also, have you tried just installing the pre-compiled binary instead of doing your own build? I ask because sometimes libraries change and introduce unexpected problems and I haven't had need to rebuild it in many months so it's possible that your build might be using a different library version than I used.

**Comment by lexhome** [comment]
Thanks for the answer, I'll try installing the precompiled binary instead of doing my own build and report back.
In addition, I inform you that apparently this is a known problem, see for example here:
https://github.com/esp8266/Arduino/issues/1094

**Comment by lexhome** [comment]
Installing the bin file using the ROM flasher did not help.
As before, when connecting to the “BG Buddy Portal” access point, the Wi-Fi connection is disconnected.


Using 'COM4' as serial port.
Connecting....%)Writing at 0x00073882... (100 %)Wrote 475312 bytes (345274 compressed) at 0x00000000 in 7.9 seconds (effective 483.7 kbit/s)...
Hash of data verified.

Leaving...
Hard Resetting...
Hard resetting via RTS pin...
Done! Flashing is complete!

Showing logs:
[21:05:38]BG Buddy
[21:05:38]Version 1.20
[21:05:38]---------------------
[21:05:38]Connecting to WiFi...
[21:05:55]Switching to Access Point mode ... Ready
[21:05:56]Starting Access Point at 10.10.10.10 ...
[21:05:56]Could not connect to WiFi - ask user to connect to Buddy.
[21:06:59]Station connected: ee:1b:1b:00:a2:5f
[21:06:59]AID: 1
[21:07:04]Station connected: ee:1b:1b:00:a2:5f
[21:07:04]AID: 1
[21:07:20]Station connected: ee:1b:1b:00:a2:5f
[21:07:20]AID: 1

**Comment by lexhome** [comment]
I'm not a programmer. I tried several options, it doesn’t help, the Wi-Fi connection still drops. 
Maybe it's a matter of features ESP 8266 Wemos D1 mini ? 
If you upload a simple sketch from the example, the Wi-Fi connection does not break (everything is fine).


#include <ESP8266WiFi.h>

void setup() {
  Serial.begin(115200);
  WiFi.mode(WIFI_AP);
  WiFi.softAP("BG Buddy Portal", "12345678");
}

void loop() {
}

**Comment by VeryKross** [comment]
Hello, I wanted to reach back out to see if you'd made any progress on this. I've just updated the binary files to version 1.3 and the focus of this update was to improve the networking, both how the WiFi was being handled and the Nightscout API calls. If you're able to, give this update a try and hopefully it will resolve any remaining issues for you.
