### ISSUE TITLE
BG Buddy Initial.... ?

### ISSUE THREAD

**Issue by spordiab** [VeryKross/BGBuddy#8]
Thank you for this great, exceptional project ^^

I have an ideaspark ESP8266MOD board with built-in screen.
The flash with the BGBuddy_v1.2_IdeaSpark.bin file works well.

Once I enter the wifi information and my web address without putting https://, I save and do a reset, when it restarts and it gives me a local IP address but then nothing, it remains like that everything the weather.

I checked several times my nightscout address was correct, on windows I copy/pasted on Chrome and I have the information from the nightscout server with my blood sugar. No need for API Token to view information.

The database is on mongodb.com and the visualization from render.com.

Can you help me please ?

![2024-05-17-15-17-40-226](https://github.com/VeryKross/BGBuddy/assets/168900799/fe80e1dd-e96e-4758-b528-668f22784e02)

**Comment by VeryKross** [comment]
Supporting this issue via email but will update this thread once we have the issue figured out.

**Comment by spordiab** [comment]
The problem was resolved.  Long live BG Buddy, thank you for everything and congratulations again for your kindness.
